# Generated by Django 5.1 on 2024-09-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orger',
            new_name='Order',
        ),
    ]
